# Generated by Django 5.2.7 on 2025-11-02 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_category_contact_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='tip',
            new_name='type',
        ),
    ]
